### ISSUE TITLE
The process activity has the same kind as the parent (receive) activity

### ISSUE THREAD

**Issue by michielvoo** [rebus-org/Rebus.OpenTelemetry#7]
I noticed that for incoming messages there are 2 activities started, one with a name that ends with receive, and another one with a name that ends with process. But on [this line](https://github.com/rebus-org/Rebus.OpenTelemetry/blob/8519b2b532e7694430e9ef320e478e9308f2f321/Rebus.Diagnostics/Diagnostics/Incoming/HandlerInvokerWrapper.cs#L37) the activity kind of the process activity is set to the same kind of its parent (receive) activity (e.g. `ActivityKind.Server` when it's a command message, or `ActivityKind.Consumer` when it is an event message). 

But I believe this is not correct, and that it should actually be set to `ActivityKind.Internal`, which according to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitykind?view=net-6.0) indicates an:

> Internal operation within an application, as opposed to operations with remote parents or children.

**Comment by zlepper** [comment]
Apparently i have push access.... @mookid8000 Maybe you should set the branch protection so we can't accidently push to master?

**Comment by zlepper** [comment]
Also, problem should be fixed, so might want to make a new build?

**Comment by michielvoo** [comment]
> Also, problem should be fixed, so might want to make a new build?

Yes please :-)

@zlepper Thank you very much for fixing this so quickly!

**Comment by mookid8000** [comment]
Cool 🙂 I've release your fix as Rebus.Diagnostics 0.0.4 and Rebus.OpenTelemetry 0.0.4, available on NuGet.org now

And regarding your push rights @zlepper , I actually think it's nice that you can do it, because then you can make changes without necessarily requiring me to be there. 😁
